/**
 * Created by Bright Huang on 11/1/14.
 */

define(['jquery', 'bootstrap', 'handlebars', 'sannong', 'validate', 'ajaxHandler', 'jqueryForm', 'formValidator',
        'selector', 'additionalMethods','eventHandler'],
    function($, bootstrap, handlebars, sannong, validate, ajaxHandler, jqueryForm, formValidator,
             selector, additionalMethods, eventHandler) {

        "use strict";

        var userProfile = {};

        userProfile.Model = {
        };

        userProfile.View = {
            newCellphoneErrorLabel: '<label id="newCellphone-error" class="error" for="newCellphone" style="display: inline-block;">手机号码已存在</label>',
            userProfileView: $("#userProfileView"),
            sideBar: $(".sidebar"),
            userManagementTab: $("#userManagementTab"),
            userProfileTab: $("#userProfileTab"),
            userPasswordTab: $("#userPasswordTab"),
            newCellphone: $("#newCellphone"),
            newCellphoneError: $("#newCellphone-error"),
            showValidationError: function(){
                userProfile.View.newCellphoneError.remove();
                userProfile.View.newCellphone.removeClass("error");
                userProfile.View.newCellphone.after(userProfile.View.newCellphoneErrorLabel);
                userProfile.View.newCellphone.addClass("error");
            },
            emptyUserProfileView: function(){
                $("#userProfileView").empty();
            },
            renderUserProfileView: function(viewName, models){
                var userProfileViewHandler = handlebars.compile($("#user-profile-template").html());
                var html = userProfileViewHandler(models.userProfile);
                $(viewName).empty();
                $(viewName).append(html);

                selector.View.addCityOptions(viewName + " #citySelect", models.cities);
                selector.View.addDistrictOptions(viewName + " #districtSelect", models.districts);
                selector.View.selectOption(viewName + " #provinceSelect", models.userProfile.companyProvince);
                selector.View.selectOption(viewName + " #citySelect", models.userProfile.companyCity);
                selector.View.selectOption(viewName + " #districtSelect", models.userProfile.companyDistrict);

                selector.initSelect('select', {
                    provinceOption: {
                        value: models.userProfile.companyProvince,
                        text: $("#provinceSelect option:selected").text()
                    },
                    cityOption: {
                        value: models.userProfile.companyCity,
                        text: $("#citySelect option:selected").text()
                    },
                    districtOption: {
                        value: models.userProfile.companyDistrict,
                        text: $("#districtSelect option:selected").text()
                    }
                });

                // TODO: As user-profile template regenerated by Handlebars js, we have to re-bind the events.
                // TODO: Consider a way to remove the code below.
                //userProfile.registerEventListener();

            }
        };

        userProfile.Controller = {
            handleFormSubmit: function(){
                var validator = formValidator.getValidator("#userProfileForm");
                if (validator === undefined){return;}
                if (validator.form() == true){
                    $("#userProfileForm").ajaxSubmit(function(message) {
                        $("#userProfileSubmit").after('<label id="userProfileSubmit-error" class="error" style="margin-top: 23px;">已保存</label>');
                        return false;
                    });
                }
            },
            handleValidationCodeClicked: function(){
                ajaxHandler.sendRequest({
                    type: "GET",
                    url: "user-profile/validateUniqueCellphone",
                    data:{cellphone: $("#newCellphone").val()},
                    success: function(response){
                        if (response == true){
                            var validator = formValidator.getValidator("#userProfileForm");
                            var newCellphoneValid = validator.element($("#newCellphone"));
                            if (validator.form() == true && newCellphoneValid == true ){
                                additionalMethods.updateTimeLabel("#action-send-code", "验证码");
                                ajaxHandler.sendRequest({
                                    url: 'user-profile/sendValidationCode',
                                    type: 'POST',
                                    data: {
                                        newCellphone: $("#newCellphone").val()
                                    },
                                    success: function(response){
                                        if (response != "") {
                                            $("#validationCode").removeAttr("disabled");
                                        } else {
                                            $("#validationCode").attr({disabled: "disabled"});
                                        }
                                    },
                                    fail: function(response){
                                        $("#validationCode").attr({disabled: "disabled"});
                                    }
                                });
                            }
                        }else{
                            userProfile.View.showValidationError();
                        }
                    },
                    fail: function(){
                        userProfile.View.showValidationError();
                    }
                });
            },
            showUserProfileView: function(userName, viewName){
                ajaxHandler.sendRequest({
                    type: "GET",
                    url: "user-personal-center/user-profile",
                    data:{userName: userName},
                    success: function(response){
                        if (response.statusCode < 2000){
                            userProfile.View.renderUserProfileView(viewName, response.models)
                        }
                    },
                    fail: function(){
                    }
                });
            }
        }

        function init(){
            eventHandler.subscribe("userProfile:handleFormSubmit", userProfile.Controller.handleFormSubmit);
            eventHandler.subscribe("userProfile:handleValidationCodeClicked", userProfile.Controller.handleValidationCodeClicked);
        }

        /*
        userProfile.registerEventListener = function(){
            $("#userProfileSubmit").click(function(){
                userProfile.Controller.handleFormSubmit();
            });

            $("#validationCodeBtn").click(function(){
                userProfile.Controller.handleValidationCodeClicked();
            });
        }
        */


        $(function() {
            selector.initSelect('select');
            //$.extend(userProfile, eventHandler);
            init();
            //userProfile.registerEventListener();
        });

        sannong.UserProfile = userProfile;
        return userProfile;

});